# web-controller.yml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/dillinger-cluster/dillinger:3.4.1
        name: web
        env:
          - name: NSOLID_APPNAME
            value: dillinger
          - name: NSOLID_HUB
            value: "nsolid-registry.nsolid:2379"
          - name: NSOLID_SOCKET
            value: "8000"
          - name: NSOLID_TAGS
            value: "nsolid-v1.4.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http-server
        volumeMounts:
          - mountPath: /opt/app/configs/dropbox/
            name: dropbox-config
          - mountPath: /opt/app/configs/github/
            name: github-config
      volumes:
        - name: dropbox-config
          secret:
            secretName: dropbox-config
        - name: github-config
          secret:
            secretName: github-config